name: Playground

on:
  workflow_dispatch:
  pull_request:
  push:
    paths: ['.github/workflows/playground.yml']

jobs:
  playground:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: './scripts'
    steps:
      - uses: actions/checkout@v3
      - uses: pl-strflt/uci/.github/actions/read-go-mod@main
        
